### PR TITLE
Major reorganization and consolidation.

### PR DESCRIPTION
**Pull request by aura**
The separate "packages" directory has been removed in favor of showing all packages, and their most-recent releases, on the home page.

The home page no longer shows "About" and "Packages" snippets at the bottom.

The home page now randomly shows a marketing phrase, "X tools for X developers", where X is "powerful", "high-quality", etc.

The "about" page now carries information that used to be on the v1 and v2 packages pages.

Removed the "frameworks" pages, which are just copies of the README files from the project repos, in favor of linking directly to the framework manuals.

Extracte inline Javascript to separate files.

Added "Aura 1.x" and "Aura 2.x" headers to the left navigation on framework manuals.

### CODE REVIEW

**Comment by aura** [comment]
@koriym and @harikt feedback please; you can see the "live" version at http://aura-framework.github.io

**Comment by koriym** [comment]
@aura Do we need a instruction for how to contribute manuals on this index page ?
http://aura-framework.github.io/manuals/

It seems only the link is enough IMHO.

**Comment by pmjones** [comment]
I transferred the test from the README to that index. I wanted to maintain as much of the content as possible. I'm OK with removing it.

**Comment by koriym** [comment]
@pmjones I see !

I like simple "dynamic" slogan on top page ;)

**Comment by harikt** [comment]
> The separate "packages" directory has been removed in favor of showing all packages, and their most-recent releases, on the home page.

Good move. No more confusion with versions.

> The home page no longer shows "About" and "Packages" snippets at the bottom.

Package structure, driving principles etc seems nice to me. May be a link to it will be good.

> The home page now randomly shows a marketing phrase, "X tools for X developers", where X is "powerful", "high-quality", etc.

It will be good to make it as a Carousel than random phrases. The same random phrase was shown to me thrice , then only it changed.

> The "about" page now carries information that used to be on the v1 and v2 packages pages.

> Removed the "frameworks" pages, which are just copies of the README files from the project repos, in favor of linking directly to the framework manuals.

ok.

> Extract inline Javascript to separate files.

ok.

> Added "Aura 1.x" and "Aura 2.x" headers to the left navigation on framework manuals.

Good.

Thanks!

**Comment by pmjones** [comment]
> It will be good to make it as a Carousel than random phrases. 

Agreed. I can do that in a later iteration.

**Pull request merged**
