### PR TITLE
Add manuals/2.0/ja/index.md

### PR DESCRIPTION
**Pull request by tdakak**
Translated into Japanese.

### CODE REVIEW

**Comment by tdakak** [comment]
文章を修正しました。ありがとうございます！

**Comment by koriym** [comment]
@tdakak ありがとうございます ！

**Comment by harikt** [comment]
Wow great! . That was a big one :+1:  .

**Comment by koriym** [comment]
@harikt This is the @tdakak's first contribute English translation. She said she is not good at English (as many Japanese devs think) before she join, BUT she did a good job. Arigato @tdakak san ! :+1:

**Comment by harikt** [comment]
Yes, you did a good job @tdakak . And thank you for your contribution. 

Every contributor will get a place at http://auraphp.com/community after we finish the translation.

Also there is @koriym to proof read even if you make any mistakes. So blame him ;-) .

**Comment by koriym** [comment]
;)

**Comment by tdakak** [comment]
@harikt @koriym
I'm very happy I can participate in the translation.
Thank you!

**Pull request merged**
