### PR TITLE
Update packages.json

### PR DESCRIPTION
**Pull request by kkeiper1103**
Fixed typographical error for the Web package in packages.json

### CODE REVIEW

**Comment by harikt** [comment]
Good catch. But my belief is packages.json is build from https://github.com/auraphp/bin/blob/890ddf2678a218e5644db4217a85c769ee0c0745/src/Command/PackagesJson.php command . So you should consider sending a patch to https://github.com/auraphp/Aura.Web/blob/1.x/composer.json#L4 which will get auto fixed.

**Comment by dstockto** [comment]
I've sent a PR for the typo fix in the originating project:

https://github.com/auraphp/Aura.Web/pull/51

**Comment by harikt** [comment]
@pmjones not sure whether this PR have something to do with the real package.json . or until a release we can merge this ?

**Comment by pmjones** [comment]
@harikt thanks for managing this, and @kkeiper1103 thanks for noticing the problem. Accepting the PR, but it'll take another release of Aura.Web 1.x for this to stay fixed.

**Pull request merged**
